

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import geopandas as gpd
from dotenv import load_dotenv
import plotly.io as pio
from utils.gemini_report import generate_state_report
from utils.pdf_report import create_pdf_report
from datetime import datetime
report_date = datetime.today().strftime("%d %B %Y")


load_dotenv()

from utils.data_loader import load_data
# from utils.gemini_report import build_report_prompt

import os

REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

CHART_DIR = "reports/charts"
os.makedirs(CHART_DIR, exist_ok=True)


def build_report_prompt(state,report_date, section_a_df, section_b_df, top_districts_raw, age_df):
    return f"""
You are a senior government data analyst preparing an official Aadhaar enrolment performance report.

IMPORTANT INSTRUCTIONS:
- Write in formal, professional government-report language.
- Use clear section headings and numbered subsections.
- Do NOT use bullet symbols like "-" or "*"; use numbered or titled paragraphs.
- Maintain a neutral, analytical tone suitable for submission to senior officials.
- Do NOT mention that this report was generated by AI.
- The report must begin with a separate front page section.

STATE DETAILS:
State Name: {state}

DATA SUMMARY (for reference only):
Reporting Coverage:
{section_a_df.to_string(index=False)}

Enrolment Volume Summary:
{section_b_df.to_string(index=False)}

Top Districts by Enrolment:
{top_districts_raw.to_string(index=False)}

Age-wise Enrolment Composition:
{age_df.to_string(index=False)}

MANDATORY REPORT STRUCTURE (FOLLOW EXACTLY):

FRONT PAGE

(The following content must appear alone on a single page.)

Title:
Aadhaar Enrolment Analysis – {state}

Subtitle:
State-wise Aadhaar Enrolment Performance Report

Report Date:
{report_date}


Prepared For:
Government of India  
Unique Identification Authority of India (UIDAI)

Prepared By:
Data Analytics Unit

--- PAGE BREAK ---

1. Executive Summary
Write a concise paragraph summarizing enrolment volume, reporting coverage, age composition, and key district-level trends.

2. Reporting Coverage and Participation
Describe reporting days, district participation, and alignment with national reporting timelines.

3. Enrolment Volume and Distribution
Discuss total enrolments, average daily enrolments, and variation across districts.

4. District-Level Performance
Highlight top-performing districts and interpret possible reasons for higher enrolment volumes.

5. Demographic (Age-wise) Composition
Analyze enrolment distribution across age groups and explain operational significance.

6. Data Limitations and Caveats
Clearly state reporting gaps, aggregation constraints, and interpretation limitations.

7. Operational Implications and Recommendations
Provide policy-relevant recommendations covering:
a) Child enrolment strategy
b) Adult enrolment gaps
c) District-level performance improvement
d) Reporting consistency and data quality assurance

FORMATTING RULES:
- Use plain text section headers (no markdown symbols).
- Maintain consistent spacing between sections.
- Keep paragraphs concise and readable.
- Do not include placeholders such as [Your Name] or [Department].

OUTPUT REQUIREMENT:
Return ONLY the final report text, fully structured and ready for direct insertion into a PDF document.
"""


def page():
    if "search_done" not in st.session_state:
        st.session_state.search_done = False

    # Custom CSS for enhanced styling
    st.markdown("""
        <style>
        /* Main container */
        .main {
            padding: 1rem 2rem;
        }
        
        /* Page title styling */
        .page-header {
            background: linear-gradient(135deg, #0891b2 0%, #06b6d4 50%, #14b8a6 100%);
            padding: 2rem;
            border-radius: 15px;
            margin-bottom: 2rem;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }
        
        .page-title {
            color: white;
            font-size: 2.2rem;
            font-weight: 700;
            margin: 0;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
        }
        
        /* Search filter section */
        .search-section {
            background: white;
            padding: 1.5rem;
            border-radius: 12px;
            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.08);
            border-left: 5px solid #0891b2;
            margin-bottom: 2rem;
        }
        
        .search-title {
            color: #0891b2;
            font-size: 1.3rem;
            font-weight: 700;
            margin-bottom: 1rem;
        }
        
        /* Section headers */
        .section-header {
            background: linear-gradient(135deg, #ecfeff 0%, #cffafe 100%);
            padding: 1rem 1.5rem;
            border-radius: 10px;
            border-left: 5px solid #06b6d4;
            margin: 1.5rem 0 1rem 0;
        }
        
        .section-title {
            color: #0891b2;
            font-size: 1.2rem;
            font-weight: 700;
            margin: 0;
        }
        
        /* Info cards */
        .info-card {
            background: white;
            padding: 1.5rem;
            border-radius: 12px;
            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.08);
            border-top: 4px solid #0891b2;
            margin: 1rem 0;
        }
        
        /* Alert boxes */
        .alert-info {
            background: linear-gradient(135deg, #ecfeff 0%, #cffafe 100%);
            border-left: 5px solid #06b6d4;
            padding: 1rem 1.5rem;
            border-radius: 8px;
            margin: 1rem 0;
        }
        
        .alert-success {
            background: linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%);
            border-left: 5px solid #10b981;
            padding: 1rem 1.5rem;
            border-radius: 8px;
            margin: 1rem 0;
        }
        
        /* Button styling */
        .stButton > button {
            background: linear-gradient(135deg, #0891b2 0%, #06b6d4 100%);
            color: white;
            border: none;
            border-radius: 8px;
            padding: 0.5rem 2rem;
            font-weight: 600;
            transition: all 0.3s;
            box-shadow: 0 2px 8px rgba(8, 145, 178, 0.3);
        }
        
        .stButton > button:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(8, 145, 178, 0.4);
        }
        
        /* Tabs styling */
        .stTabs [data-baseweb="tab-list"] {
            gap: 8px;
            background: linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%);
            padding: 0.5rem;
            border-radius: 10px;
        }
        
        .stTabs [data-baseweb="tab"] {
            height: 50px;
            background-color: white;
            border-radius: 8px;
            color: #0891b2;
            font-weight: 600;
            padding: 0 2rem;
            border: 2px solid transparent;
        }
        
        .stTabs [aria-selected="true"] {
            background: linear-gradient(135deg, #0891b2 0%, #06b6d4 100%);
            color: white;
            border: 2px solid #0891b2;
        }
        </style>
    """, unsafe_allow_html=True)
    
    # ----------------------------
    # Load data
    # ----------------------------
    df = load_data()
    df['date'] = pd.to_datetime(df['date'])

    # Page header
    st.markdown("""
        <div class="page-header">
            <h1 class="page-title">🏛️ State-wise Aadhaar Enrolment Analysis</h1>
        </div>
    """, unsafe_allow_html=True)

    # ----------------------------
    # States with Geomap support
    # ----------------------------
    GEO_AVAILABLE_STATES = ['Andhra Pradesh ',
 'Assam',
 'Bihar',
 'Chattisgarh',
 'Delhi',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammukashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'North Eastern',
 'Odisha',
 'Punjab',
 'Rajasthan',
 'Tamilnadu',
 'Telangana',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

    # =====================================================
    # PREPARE STATE ORDER (SORT BY TOTAL ENROLMENT)
    # =====================================================
    state_order = (
        df.groupby('state')['total_daily_enrolement']
        .sum()
        .sort_values(ascending=False)
        .index
        .tolist()
    )

    # =====================================================
    # STATE FILTER (ENHANCED SEARCH SECTION)
    # =====================================================
    st.markdown("""
        <div class="search-section">
            <h3 class="search-title">🔎 State Filter</h3>
        </div>
    """, unsafe_allow_html=True)

    filter_col1, filter_col2 = st.columns([4, 1])

    with filter_col1:
        state = st.selectbox(
            "Select State",
            options=state_order,
            index=None,
            placeholder="🔍 Type to search state...",
            label_visibility="collapsed"
        )

    with filter_col2:
        if st.button("🔎 Search", use_container_width=True):
            st.session_state.search_done = True

    if not st.session_state.search_done:
        st.markdown("""
            <div class="alert-info">
                <strong>ℹ️ Getting Started:</strong> Select a state and click <strong>Search</strong> to view detailed analysis.
            </div>
        """, unsafe_allow_html=True)
        return


    if state is None:
        st.markdown("""
            <div class="alert-info">
                <strong>⚠️ Notice:</strong> Please select a state before clicking Search.
            </div>
        """, unsafe_allow_html=True)
        return

    # ----------------------------
    # Filter data
    # ----------------------------
    df_state = df[df['state'] == state].copy()

    if df_state.empty:
        st.warning("No data available for this state.")
        return

    # Show success message
    st.markdown(f"""
        <div class="alert-success">
            <strong>✅ Analysis Ready:</strong> Displaying comprehensive insights for <strong>{state}</strong>
        </div>
    """, unsafe_allow_html=True)

    # ----------------------------
    # National reference
    # ----------------------------
    national_reporting_days = df['date'].nunique()

    # =====================================================
    # SECTION A — COVERAGE OVERVIEW
    # =====================================================
    reporting_days = df_state['date'].nunique()
    date_range = (df_state['date'].min(), df_state['date'].max())
    districts_reporting = df_state['district'].nunique()
    total_enrolments = df_state['total_daily_enrolement'].sum()

    avg_enrolments_per_district_day = (
        total_enrolments / (reporting_days * districts_reporting)
    )

    section_a_df = pd.DataFrame({
        "Metric": [
            "Reporting days",
            "National reporting days",
            "Districts reporting at least once",
            "Reporting date range",
            "Avg enrolments per district per reporting day"
        ],
        "Value": [
            reporting_days,
            national_reporting_days,
            districts_reporting,
            f"{date_range[0].date()} to {date_range[1].date()}",
            round(avg_enrolments_per_district_day, 2)
        ]
    })

    st.markdown("""
        <div class="section-header">
            <h3 class="section-title">A. Reporting Coverage Overview</h3>
        </div>
    """, unsafe_allow_html=True)
    st.dataframe(section_a_df, use_container_width=True, hide_index=True)

    # =====================================================
    # SECTION B — VOLUME SUMMARY
    # =====================================================
    avg_enrolments_per_day = total_enrolments / reporting_days

    section_b_df = pd.DataFrame({
        "Metric": [
            "Total enrolments (reported days only)",
            "Average enrolments per reported day",
            "Reporting days",
            "Districts reporting"
        ],
        "Value": [
            f"{int(total_enrolments):,}",
            f"{round(avg_enrolments_per_day, 2):,}",
            reporting_days,
            districts_reporting
        ]
    })

    st.markdown("""
        <div class="section-header">
            <h3 class="section-title">B. Enrolment Volume Summary</h3>
        </div>
    """, unsafe_allow_html=True)
    st.dataframe(section_b_df, use_container_width=True, hide_index=True)

    # =====================================================
    # NEW SECTION — TOP 7 DISTRICTS
    # =====================================================
    st.markdown("""
        <div class="section-header">
            <h3 class="section-title">📊 Top 7 Districts by Total Enrolment</h3>
        </div>
    """, unsafe_allow_html=True)

    # Calculate top 5 districts
    top_districts_raw = (
        df_state.groupby('district')['total_daily_enrolement']
        .sum()
        .sort_values(ascending=False)
        .head(7)
        .reset_index()
    )
    
    # Create display dataframe
    top_districts_display = top_districts_raw.copy()
    top_districts_display.columns = ['District', 'Total Enrolment']
    top_districts_display['Rank'] = range(1, len(top_districts_display) + 1)
    top_districts_display['Total Enrolment'] = top_districts_display['Total Enrolment'].apply(lambda x: f"{int(x):,}")
    top_districts_display = top_districts_display[['Rank', 'District', 'Total Enrolment']]

    # Create two columns for dataframe and chart
    col_table, col_chart = st.columns([1.2, 1.8])

    with col_table:
        st.dataframe(
            top_districts_display,
            use_container_width=True,
            hide_index=True,
            height=280
        )

    with col_chart:
        # Use the raw data for chart
        chart_data = top_districts_raw.copy()
        chart_data.columns = ['district', 'total_enrolment']
        
        fig_top_districts = px.bar(
            chart_data,
            y='district',
            x='total_enrolment',
            orientation='h',
            labels={
                'district': '',
                'total_enrolment': 'Total Enrolment'
            },
            color='total_enrolment',
            color_continuous_scale='Teal',
            text='total_enrolment'
        )
        
        fig_top_districts.update_layout(
            showlegend=False,
            template='plotly_white',
            height=280,
            yaxis={'categoryorder': 'total ascending'},
            margin=dict(l=10, r=10, t=30, b=10),
            xaxis_title="Total Enrolment"
        )
        
        fig_top_districts.update_traces(
            texttemplate='%{text:,.0f}',
            textposition='outside',
            textfont=dict(size=11)
        )
        
        fig_top_districts.update_coloraxes(showscale=False)

        st.plotly_chart(fig_top_districts, use_container_width=True)
        st.markdown(
    "**This bar chart ranks the top seven districts in selected state by average Aadhaar enrolments per reported day, "
    "considering only districts with ≥30% reporting coverage to ensure comparability.**"
)

    # =====================================================
    # SECTION C — VISUALIZATIONS WITH TABS
    # =====================================================
    st.markdown("""
        <div class="section-header">
            <h3 class="section-title">C. Visual Analytics</h3>
        </div>
    """, unsafe_allow_html=True)

    # Prepare all visualizations data
    # Daily Trends
    daily = (
        df_state.groupby('date')
        .agg(
            total_enrolments=('total_daily_enrolement', 'sum'),
            reporting_districts=('district', 'nunique')
        )
        .reset_index()
    )

    # Weekday Pattern
    weekday_order = [
        'Monday', 'Tuesday', 'Wednesday',
        'Thursday', 'Friday', 'Saturday', 'Sunday'
    ]

    weekday_df = (
        df_state.groupby('day_name')['total_daily_enrolement']
        .sum()
        .reindex(weekday_order)
        .reset_index()
    )

    # District Coverage
    district_stats = (
        df_state.groupby('district')
        .agg(
            total_enrolments=('total_daily_enrolement', 'sum'),
            reporting_days=('date', 'nunique')
        )
        .reset_index()
    )

    district_stats['avg_enrolments_per_reported_day'] = (
        district_stats['total_enrolments'] /
        district_stats['reporting_days']
    )

    # Age Composition
    age_df = pd.DataFrame({
        "Age Group": ["0–5 years", "5–17 years", "18+ years"],
        "Enrolments": [
            df_state['age_0_5'].sum(),
            df_state['age_5_17'].sum(),
            df_state['age_18_greater'].sum()
        ]
    })

    age_df["Share (%)"] = (
        age_df["Enrolments"] / total_enrolments * 100
    ).round(2)

    # Create tabs for visualizations
    tab1, tab2, tab3, tab4 = st.tabs([
        "📈 Daily Trends", 
        "📅 Weekly Pattern", 
        "🏙️ District Coverage", 
        "👥 Age Composition"
    ])

    with tab1:
        fig_daily = go.Figure()

        fig_daily.add_trace(go.Scatter(
            x=daily['date'],
            y=daily['total_enrolments'],
            mode='lines+markers',
            name='Total Enrolments',
            line=dict(color='#0891b2', width=3),
            marker=dict(size=6)
        ))

        fig_daily.add_trace(go.Scatter(
            x=daily['date'],
            y=daily['reporting_districts'],
            mode='lines+markers',
            name='Reporting Districts',
            yaxis='y2',
            line=dict(color='#14b8a6', width=3),
            marker=dict(size=6)
        ))

        fig_daily.update_layout(
            title=f"{state}: Daily Aadhaar Enrolments & Reporting Coverage",
            xaxis_title="Date",
            yaxis=dict(title="Total Enrolments"),
            yaxis2=dict(
                title="Reporting Districts",
                overlaying="y",
                side="right"
            ),
            hovermode='x unified',
            template='plotly_white',
            height=500
        )

        st.plotly_chart(fig_daily, use_container_width=True)
        
        st.markdown(
            "**This time-series plot tracks total daily Aadhaar enrolments in selected state alongside the number of reporting "
            "districts, highlighting how enrolment volumes change with reporting coverage over time.**"
        )

    with tab2:
        fig_weekday = px.bar(
            weekday_df,
            x='day_name',
            y='total_daily_enrolement',
            title=f"{state}: Total Enrolments by Day of Week",
            color='total_daily_enrolement',
            color_continuous_scale='Teal',
            labels={'total_daily_enrolement': 'Total Enrolments', 'day_name': 'Day of Week'}
        )
        
        fig_weekday.update_layout(
            showlegend=False,
            template='plotly_white',
            height=500
        )

        st.plotly_chart(fig_weekday, use_container_width=True)
        st.markdown(
    "**This bar chart aggregates total reported Aadhaar enrolments in selected state by day of the week across all "
    "reporting dates.**"
)

    with tab3:
        fig_scatter = px.scatter(
            district_stats,
            x='reporting_days',
            y='avg_enrolments_per_reported_day',
            trendline='lowess',
            title=f"{state}: Reporting Coverage vs Avg Daily Enrolment",
            labels={
                'reporting_days': 'Reporting Days',
                'avg_enrolments_per_reported_day': 'Avg Daily Enrolment'
            },
            color_discrete_sequence=['#0891b2']
        )
        
        fig_scatter.update_layout(
            template='plotly_white',
            height=500
        )

        st.plotly_chart(fig_scatter, use_container_width=True)
        st.markdown(
    "**This scatter plot compares the number of reporting days per district with its average daily Aadhaar enrolments, "
    "assessing the effect of uneven reporting coverage on observed enrolment intensity.**"
)

    with tab4:
        fig_age = px.pie(
            age_df,
            values="Share (%)",
            names="Age Group",
            hole=0.4,
            title=f"{state}: Age-wise Enrolment Composition",
            color_discrete_sequence=['#0891b2', '#06b6d4', '#14b8a6']
        )
        
        fig_age.update_layout(
            template='plotly_white',
            height=500
        )

        st.plotly_chart(fig_age, use_container_width=True)
        
        st.markdown(
            "**This pie chart displays the proportional distribution of Aadhaar enrolments in selected state across three age "
            "groups (0–5, 5–17, and 18+ years) using reported days only.**"
        )

    # =====================================================
    # SECTION D — PINCODE MAP (DIRECT DISPLAY)
    # =====================================================
    st.markdown("""
        <div class="section-header">
            <h3 class="section-title">D. Spatial Distribution (Pincode Level)</h3>
        </div>
    """, unsafe_allow_html=True)

    if state not in GEO_AVAILABLE_STATES:
        st.markdown("""
            <div class="alert-info">
                <strong>🗺️ Geospatial Availability:</strong> Maps are currently available only for: <br>
                """ + ", ".join(GEO_AVAILABLE_STATES) + """
            </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown("""
            <div class="alert-success">
                <strong>🟢 Geomap Available:</strong> Displaying pincode-level spatial visualization
            </div>
        """, unsafe_allow_html=True)

        try:
            pincode_gdf = gpd.read_file(
                "data/All_India_pincode_Boundary-19312.geojson"
            )

            pincode_stats = (
                df_state.groupby('pincode')
                .agg(
                    total_enrolments=('total_daily_enrolement', 'sum'),
                    reporting_days=('date', 'nunique')
                )
                .reset_index()
            )

            pincode_stats['avg_enrolments_per_reported_day'] = (
                pincode_stats['total_enrolments'] /
                pincode_stats['reporting_days']
            )

            pincode_gdf = pincode_gdf.rename(columns={'Pincode': 'pincode'})
            pincode_gdf['pincode'] = pincode_gdf['pincode'].astype(str)
            pincode_stats['pincode'] = pincode_stats['pincode'].astype(str)

            state_pincode_gdf = pincode_gdf[
                pincode_gdf['Circle']
                .str.lower()
                .str.contains(state.lower(), na=False)
            ]

            pincode_map = state_pincode_gdf.merge(
                pincode_stats,
                on='pincode',
                how='left'
            )

            pincode_map['log_avg_enrolments'] = np.log1p(
                pincode_map['avg_enrolments_per_reported_day']
            )

            fig, ax = plt.subplots(figsize=(14, 16))

            pincode_map.plot(
                column='log_avg_enrolments',
                cmap='viridis',
                linewidth=0.05,
                ax=ax,
                legend=True,
                missing_kwds={"color": "lightgrey"},
                legend_kwds={'label': 'Log(Avg Enrolments per Day)', 'shrink': 0.8}
            )

            ax.set_title(
                f"{state}: Pincode-level Aadhaar Enrolment Intensity",
                fontsize=18,
                fontweight='bold',
                pad=20
            )
            ax.axis('off')

            st.pyplot(fig)
            st.markdown(
    "**This choropleth map visualizes log-scaled average Aadhaar enrolments per reported day at the pincode level across "
    "selected state, using coverage-aware aggregation to control for uneven reporting.**"
)

        except Exception as e:
            st.markdown("""
                <div class="alert-info">
                    <strong>⚠️ Map Loading Issue:</strong> Pincode map could not be rendered. Please check the data file.
                </div>
            """, unsafe_allow_html=True)
            st.text(str(e))

    


    st.markdown("### 📥 Download PDF Report")

    if st.button("📄 Generate & Download PDF"):

        with st.spinner("Generating PDF report..."):

            # 1️⃣ Generate text report
            prompt = build_report_prompt(
                    state,
                    report_date,
                    section_a_df,
                    section_b_df,
                    top_districts_raw,
                    age_df
            )

            report_text = generate_state_report(prompt)

            # 2️⃣ Save charts
            chart_paths = []

            pio.write_image(fig_daily, f"{CHART_DIR}/daily.png")
            chart_paths.append(("Daily Enrolment Trend", f"{CHART_DIR}/daily.png"))

            pio.write_image(fig_weekday, f"{CHART_DIR}/weekday.png")
            chart_paths.append(("Weekly Pattern", f"{CHART_DIR}/weekday.png"))

            pio.write_image(fig_scatter, f"{CHART_DIR}/coverage.png")
            chart_paths.append(("Coverage vs Intensity", f"{CHART_DIR}/coverage.png"))

            pio.write_image(fig_age, f"{CHART_DIR}/age.png")
            chart_paths.append(("Age Composition", f"{CHART_DIR}/age.png"))

            # 3️⃣ Create PDF
            pdf_path = f"reports/{state.replace(' ', '_')}_Aadhaar_Report.pdf"

            create_pdf_report(
                 pdf_path,
    report_text,
    chart_paths
            )

        with open(pdf_path, "rb") as f:
            st.download_button(
                "⬇️ Download PDF",
                f,
                file_name=os.path.basename(pdf_path),
                mime="application/pdf"
            )
